cms:
  contentBaseUri: https://harpercollinspoc.com/schemas
  clientId: 
  clientSecret: 
  damUsername: 
  damPassword: 
  hubId: 
  hubName: 
  accountName: 
  stagingApi: 
  contentApi: 
dam:
  username:
  password:
  source:
    type: s3
    bucket: demo-dam-assets-pwa
    region: eu-west-3
app:
  appName: amp-pwa-harpercollins
  scope: amplience-presales