cms:
  contentBaseUri: https://harpercollinspoc.com/schemas
  clientId: 
  clientSecret: 
  damUsername: 
  damPassword: 
  hubId: 
  hubName: harpercollinspoc
  accountName: harper_collins
  stagingApi: 17dqy0jkdvn1i1y1igzbz1d2r7.staging.bigcontent.io
  contentApi: harpercollinspoc.cdn.content.amplience.net
dam:
  source:
    type: s3
    bucket: demo-dam-assets-pwa
    region: eu-west-3
app:
  appName: amp-pwa-harpercollins
  scope: amplience-presales